baseURL = "https://fanxgg.github.io/TurboTides"
canonifyURLs = true
title = "TURBOTIDES"
author = "Taize Technology"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true


# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

# Allow rendering of raw HTML in Markdown files
[markup]
  goldmark = { renderer = { unsafe = true } }

[params]

  showBlog = true
  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.svg"
    alt = "TurboTides Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-10"

  [params.site]
    name = "TURBOTIDES"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true
    material = true

  [params.homepage_meta_tags]
    meta_description = "TurboTides - Professional CAE industrial software solution to assist enterprises in efficient simulation and optimization design"
    meta_og_title = "TurboTides"
    meta_og_type = "website"
    meta_og_url = "https://fanxgg.github.io/TurboTides"
    meta_og_image = "https://github.com/fanxgg/TurboTides/tree/main/img/tn.png"
    meta_og_description = "TurboTides provides efficient CAE simulation and optimization software to help enterprises improve design efficiency"


[menu]

  [[menu.main]]
    identifier = "products"
    name = "Products"
    url = "/products/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Case Studies"
    url = "/blog/"
    weight = 2

#  [[menu.main]]
#    identifier = "about"
#    name = "About Us"
#    url = "/about/"
#    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "About Us"
    url = "/contact/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Return"
    url = "/"
    pre = "<i class='fas fa-home text-2xl'></i>"
      weight = 2
